name: Flutter CI

on:
  push:
    branches:
      - varun
  workflow_dispatch:  # Allows manual triggering

jobs:
  delete-releases:
    runs-on: ubuntu-latest
    steps:
      - name: List and delete all releases
        run: |
          releases=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[].id')
          for release in $releases; do
            echo "Deleting release $release"
            curl -X DELETE -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/$release
          done
        env:
          TOKEN: ${{ secrets.TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: delete-releases
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21.0.1'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build apk --release --split-per-abi

      - uses: ncipollo/release-action@v1
        with:
          name: release-apk
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0.0.1
          token: ${{ secrets.TOKEN }}
